### ISSUE TITLE
Removal of Python2 breaks popular plugin(s)

### ISSUE THREAD

**Issue by FlyveHest** [linuxserver/docker-nzbget#107]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Update the docker image should have nzbget and core plugins continue to work

## Current Behavior
After the removal of Python2 VideoSort, a core plugin in NZBGet stops working, most likely because it is somewhat old and not Python3 compatible-

## Steps to Reproduce

1. Install latest linuxserver.io nzbget docker container
2. Install VideoSort from https://github.com/nzbget/VideoSort and configure

I rolled back to linuxserver/nzbget:amd64-v21.0-ls53 to get the plugin to work again.

## Docker logs
No relevant docker log, but this is the log from nzbget itself (probably pointless here)

```
VideoSort: SyntaxError: invalid syntax
VideoSort: ^
VideoSort: ep_prefix = episode_separator if episode_num_all <> '' else ''
VideoSort: File "/workdir/scripts/videosort/VideoSort.py", line 814
```

**Comment by tobbenb** [comment]
You can use the customisation option o add back python 2. 
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
Python 2 is EOL and we deceided to remove it. Please ask the plugin author toake it python 3 compatible.
