### ISSUE TITLE
dropping python2 broke all the post processing scripts

### ISSUE THREAD

**Issue by zombiehoffa** [linuxserver/docker-nzbget#109]
You guys dropped python2 which broke most of the included post processing scripts ( dirwatch.py, fakedetector.py, passworddetector.py, resetdatetime.py). it would be great if you could convert this to use python 3 or continue to include support for python2.

**Comment by aptalca** [comment]
You can contact the maintainers of those scripts. Py2 is EOL, which was announced many years ago. See here for more info: https://github.com/linuxserver/docker-nzbget/issues/104#issuecomment-641517294
