### ISSUE TITLE
Latest version breaks python extensions

### ISSUE THREAD

**Issue by typhune** [linuxserver/docker-nzbget#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The latest version which does away with python 2 breaks the extensions that only support python 2.  Namely:
Failurelink
FakeDetector
Passworddetector
Unzip

**Comment by tobbenb** [comment]
You might want to check closed issues before making a new.

**Comment by typhune** [comment]
> You might want to check closed issues before making a new.

Apologies, still getting familiar with github.

**Comment by tobbenb** [comment]
No problem. They are hidden unless you actively choose them.
