### ISSUE TITLE
Could not resolve hostname news.newshosting.com: ErrNo -3, Try again

### ISSUE THREAD

**Issue by Zeusy123** [linuxserver/docker-nzbget#113]
Both of my (hertsner) servers with nzbget stopped downloading last night.

error in logs is : Could not resolve hostname news.newshosting.com: ErrNo -3, Try again

But when i force another newgroup..still wont download anything.

Any ideas?

**Comment by j0nnymoe** [comment]
Try changing your dns on your server.

**Comment by Zeusy123** [comment]
> Try changing your dns on your server.

Thanks for the reply bro, 

but would this happen on both servers at same time??

Also what command should i use to change dns??

**Comment by Zeusy123** [comment]
erm when i do:
 # ping news.newshosting.com
ping: news.newshosting.com: Temporary failure in name resolution

**Comment by j0nnymoe** [comment]
No idea but it looks like an issue with your host and not container related.

**Comment by ismay** [comment]
I've had this as well. Multiple times. I thought it was my dns at first (Mullvad, 193.138.218.74), so I switched to Cloudflare (1.1.1.1), but now I'm having the exact same issue with Cloudflare as well.

The host (CentOS 7) does not have any issues resolving DNS with `1.1.1.1`, but certain linuxserver docker containers do (nzbget, beets). Ping from the nzbget container:

```
docker exec -it nzbget /bin/bash
# ping google.com
ping: bad address 'google.com'
# cat /etc/resolv.conf 
search home
nameserver 127.0.0.11
options ndots:0
```

Ping from the host OS:

```
$ ping google.com
PING google.com (172.217.19.206) 56(84) bytes of data.
64 bytes from ams16s31-in-f14.1e100.net (172.217.19.206): icmp_seq=1 ttl=117 time=16.9 ms
64 bytes from ams16s31-in-f14.1e100.net (172.217.19.206): icmp_seq=2 ttl=117 time=17.2 ms
64 bytes from ams16s31-in-f14.1e100.net (172.217.19.206): icmp_seq=3 ttl=117 time=17.6 ms
64 bytes from ams16s31-in-f14.1e100.net (172.217.19.206): icmp_seq=4 ttl=117 time=10.3 ms
$ cat /etc/resolv.conf 
# Generated by NetworkManager
search home
nameserver 1.1.1.1
```

So it seems to be unrelated to the DNS server being used. It does not happen with all containers at the same time. Plex is still fine for example. And also nzbget is sometimes. A minimal reproduction from the host OS is:

```
$ docker run busybox nslookup google.com
Server:		1.1.1.1
Address:	1.1.1.1:53

Non-authoritative answer:
*** Can't find google.com: No answer

*** Can't find google.com: No answer
```

**Comment by ismay** [comment]
Ok. I finally figured it out. This was happening because I had the adguard docker container running on the same host. After turning it off everything immediately worked again.
