### ISSUE TITLE
VideoSort.py can't find guessit when running in a Docker container

### ISSUE THREAD

**Issue by adefaria** [linuxserver/docker-nzbget#114]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After downloading a file it should run VideoSort.py

## Current Behavior
root@nzbget:/downloads/scripts# python VideoSort.py                             
Traceback (most recent call last):                                              
  File "VideoSort.py", line 273, in <module>                                    
    import guessit                                                              
ModuleNotFoundError: No module named 'guessit'                                  
root@nzbget:

## Steps to Reproduce

1. Start a bash shell in the container
2. cd /downloads/scripts (or wherever you placed VideoSort)
3. Execute python VideoSort.py

## Environment
root@nzbget:/downloads/scripts# uname -a                                        
Linux nzbget 4.4.59+ #25426 SMP PREEMPT Wed Jul 8 03:21:29 CST 2020 x86_64 GNU/L
inux                                                                            
root@nzbget:/downloads/scripts#

Docker was installed via Synology's DSM package manager
The image was pulled from the official Docker registry

## Command used to create docker container (run/create/compose/screenshot)
![nzbget docker 1](https://user-images.githubusercontent.com/2692127/96490850-3f815680-11f6-11eb-9c37-2a2cf4ede1c8.png)
![nzbget docker 2](https://user-images.githubusercontent.com/2692127/96490886-4e680900-11f6-11eb-815c-318fc4edb8d8.png)

**Comment by Roxedus** [comment]
You should set up a startup script that installs guesit with pip. https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
