### ISSUE TITLE
All downloads fail with URLLIB2 error

### ISSUE THREAD

**Issue by etsolow** [linuxserver/docker-nzbget#135]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Downloads should succeed. 
## Current Behavior

All downloads fail and generate an error about URLLIB2 missing. 
## Steps to Reproduce

1. Deploy "latest"-tagged image.
2. Download a file. 
3. See download fail with URLLIB2 error. 

## Environment
**OS:** Synology DSM 6.2.4-25556
**CPU architecture:** x86_64
**How docker service was installed:** NAS OS provided

## Command used to create docker container (run/create/compose/screenshot)

{
   "cap_add" : [],
   "cap_drop" : [],
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "PS1",
         "value" : "$(whoami)@$(hostname):$(pwd)$ "
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "PUID",
         "value" : "-redacted-"
      },
      {
         "key" : "PGID",
         "value" : "-redacted-"
      },
      {
         "key" : "TZ",
         "value" : "-redacted-"
      }
   ],
   "exporting" : false,
   "id" : "-redacted-",
   "image" : "linuxserver/nzbget:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "linuxserver-nzbget-latest",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 6789,
         "host_port" : 6789,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/-redacted-/Music",
         "mount_point" : "/-redacted-MUSIC",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/Download",
         "mount_point" : "/downloads",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/LIDARR-LIBRARY",
         "mount_point" : "/music",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/Movies",
         "mount_point" : "/-redacted-MOVIES",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/Download",
         "mount_point" : "/-redacted-DOWNLOAD",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/Pickup",
         "mount_point" : "/-redacted-PICKUP",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/NZBTemp",
         "mount_point" : "/-redacted-NZBTEMP",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/PLEXDATA/TV-OLD",
         "mount_point" : "/-redacted-",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/PLEXDATA/TV-NEW",
         "mount_point" : "/-redacted-",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/-redacted-/TV",
         "mount_point" : "/-redacted-TV",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/nzbget",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}
## Docker logs

n/a

**Comment by Roxedus** [comment]
Please finish the issue template.

**Comment by etsolow** [comment]
Sorry I already rolled back to a previous image so I can no longer get relevant log files.

**Comment by etsolow** [comment]
Add'l information: roll-back to linuxserver/nzbget:amd64-v21.1-r2311-ls46 resolves the issue.

**Comment by Roxedus** [comment]
Going back to tag that's over a year old is not a fix. From what I can tell you are trying to use python2, a package that was EOL almost 6 months before that tag saw the day.

**Comment by etsolow** [comment]
What do you mean I'm using Python 2? The "latest" tagged image is trying to use Python 2, and failing. The *older* image works correctly. One of us is super confused.

**Comment by Roxedus** [comment]
You probably have post processing scripts. NZBGet does not need or use Python to do anything.

**Comment by etsolow** [comment]
So... until last week the longtime current linuxserver NZBGet image was able to run Python post-processing scripts. Now, it no longer can. Issue closed? I'm pretty sure NZBGet didn't lose that capability in the latest point release, but OK, will look for a new image to use, I guess.

**Comment by j0nnymoe** [comment]
No, we dropped support for python2 months ago. You need to update your post processing scripts to python3.

**Comment by Roxedus** [comment]
Thats not what I am saying at all. I use python3 post processing scripts just fine. Im trying to hint that the scripts you are using needs to be updated.

**Comment by etsolow** [comment]
OK. Thank you. I daresay that could have been stated a little clearer up front.
