### ISSUE TITLE
nzb2Media scripts now say "python2 No such file or directory"

### ISSUE THREAD

**Issue by iDVB** [linuxserver/docker-nzbget#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

python script calls that used to work, should continue to work.

## Current Behavior

It appears the path for python and perhaps the version have been updated. 
Now [nzb2Media scripts](https://github.com/clinton-hall/nzbToMedia) are failing with:
> python2: No such file or directory

It seems like a symlink can fix the issue, but since this is docker, not sure what the best way to handle it would be for anyone that may also be having this issue. [Similar to this issue](https://github.com/clinton-hall/nzbToMedia/issues/454).

**Comment by aptalca** [comment]
Python3 is already symlinked
https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile#L97
