### ISSUE TITLE
cacert.pem needs to be replaced

### ISSUE THREAD

**Issue by cbenard** [linuxserver/docker-nzbget#140]
[Source](https://github.com/nzbget/nzbget/issues/784#issuecomment-931609658) - expiry of root used by Let's Encrypt

It's been fixed in v21.2-r2333 (testing), but it can be backported with the fix linked above (replacing the cacert.pem in the Dockerfile).

Please update the Dockerfile and push so we can just pull a new image without having to do [this](https://www.reddit.com/r/usenet/comments/pyo27t/ndngd_lets_encrypt_root_certificate_expiration/hex3y16/) on every instance.

**Comment by Roxedus** [comment]
Have you confirmed this is a real issue with our image?

**Comment by cbenard** [comment]
I have not. I already updated my cacert.pem from their provided one with `exec -it` + `curl`. I did diff it to what they provided and it is in fact different.

**Comment by Roxedus** [comment]
Can you place try with the certificate that comes with the image? As I do not think our image is affected, mine has been running uninterrupted.

**Comment by phybersplice** [comment]
Looks like it is with the image.  
NZBGET has updated their package.

https://nzbget.net/history-latest-testing

**Comment by cbenard** [comment]
I can't test at this point. I was just raising the issue since they changed their software distribution and linuxserver's hasn't changed since then. You can close it if it isn't an issue for you after all.

**Comment by Roxedus** [comment]
I find no cause of this ever being a issue with our container, however I have no issue being told otherwise.

**Comment by cbenard** [comment]
@phybersplice seemed to indicate it was a problem with theirs.
