### ISSUE TITLE
NZBGET is inaccessible since today's update

### ISSUE THREAD

**Issue by so7ow** [linuxserver/docker-nzbget#148]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

NZBGET should be accessible over the network in a browser. It worked properly for months until today's update.

## Current Behavior

NZBGET is inaccessible. Various errors, depending on web browser.

Google Chrome: This site can’t be reached The connection was reset.
Microsoft Edge: Hmmm… can't reach this page.The connection was reset.
## Steps to Reproduce

1. Browse to NZBGET url in any web browser.
2. View failure message.
3.
4.

## Environment
**OS:** DSM 7.1-42661 Update 4.
**CPU architecture:** x86_64
**How docker service was installed:**

Running on Synology 1815+

## Command used to create docker container (run/create/compose/screenshot)

<img width="1106" alt="Cursor_and_SOLOWNAS - Synology DiskStation" src="https://user-images.githubusercontent.com/633079/184167432-ba343872-dfc8-4938-9500-458f6aa48fde.png">

## Docker logs

https://pastebin.com/fW6a42y7

**Comment by j0nnymoe** [comment]
Invalid post as you haven't provided all the information requested but it looks to be failing on some custom scripts you have.

**Comment by so7ow** [comment]
Sorry, where should I see what information is requested?

I don't have any custom scripts in place, at least that I know of. In fact, I just checked the conf file to find the script location and there is not even a ${MainDir}/scripts folder to clear out.

**Comment by j0nnymoe** [comment]
When you open an issue, there is a template with information that we ask for.

If you look at your logs, it shows a custom script trying to install other things which is likely why this is failing.

**Comment by so7ow** [comment]
I've filled in the template. Not sure why it wasn't presented to me when I created this issue.
