### ISSUE TITLE
Problems with nzbget.lock

### ISSUE THREAD

**Issue by dawtmaytrikx** [linuxserver/docker-nzbget#15]
Had to restart the container today after disabling one of the servers in the UI because I had used up the quota and NZBGet wouldn't reload afterwards as it usually did. I promptly got the following error message:

> cat: /downloads/nzbget.lock: No such file or directory
> tail: : invalid PID

So I changed the location of the lock-file in the config to /config/nzbget.lock, at which point I started getting this error:

> Starting daemon failed: could not acquire lock on lock-file /config/nzbget.lock

Checked all the permissions, they're fine. I changed the location of the lock-file back to /downloads/nzbget.lock and copied over the file to that location, and now I'm getting this error:

> Starting daemon failed: could not create lock-file /config/downloads/nzbget.lock

When I point the config to the that location, I get the first error again. Same thing when I comment out the location of the lock-file in the config.

WTF is going on here?

**EDIT: Never mind. Apparently there was some issue with my queue that caused NZBGet to go haywire. Deleted it, and everything's back to normal.**

**Comment by lonix** [comment]
It recently had slot of updates try and repulsive the container please :)  

Sendt fra min iPhone

**Comment by JTarasovic** [comment]
Yeah, there were a number of changes to the image over the last couple of weeks trying to handle the lock file a little bit better.  If you're still having problems, try blowing away the container, pulling the latest image and re-creating the container.

```bash
docker stop sonarr && docker rm sonarr && docker pull linuxserver/sonarr
```

**Comment by zaggash** [comment]
> `docker stop sonarr && docker rm sonarr && docker pull linuxserver/sonarr`

Wrong topic I must say :)

**Comment by zaggash** [comment]
Once again, this may be better with the coming update
#17
