### ISSUE TITLE
Provide an image tag following NZBGet's two number versioning system

### ISSUE THREAD

**Issue by calvinbui** [linuxserver/docker-nzbget#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I'd like to request a docker image tag for NZBGet to follow their two number versioning system, i.e. `21.1`. While NZBGet doesn't get many updates these days, it would still be preferable to pin to a version.

Other repositories from LinuxServer.io such as Sonarr, Radarr, etc. provide a tag with just the version, albeit they follow SemVer.

## Current Behavior

Only tags provided are:

- `21.1.<date>`
- `version-v21.1`
- `v21.1-ls<build>`
- `<arch>-21.1.<date>`

**Comment by Roxedus** [comment]
We are not able to customize tagging strategy per repository with our current pipeline.

**Comment by aptalca** [comment]
The tag `version-v21.1` is your best bet for pinning to a specific nzbget version
