### ISSUE TITLE
Unrar and 7za binaries as symbolic links - Proxmox backup fails

### ISSUE THREAD

**Issue by thehijacker** [linuxserver/docker-nzbget#152]
## Desired Behavior

Everytime I update the docker container for nzbget, Proxmox that runs LXC with Docker failes to backup it. Problem is with /app/nzbget/unrar and /app/nzbget/7za that are symbolic links and rsync that is used to backup LXC fails when copying them. I always need to enter the container FS and remove this two symbolic links. Unrar and 7za are still working for me even if I delete this two symbolic links.

## Current Behavior

unrar and 7za are symbolic links thats fails to backup using Proxmox backup which uses rsync.

**Comment by aptalca** [comment]
1. You don't need to back up anything inside the container. The container is ephemeral. Only back up the host mounts that contain persistent data
2. Rsync has no issues with symlinks as long as you use the correct arguments
3. This is not an appropriate issue for this repo as it's not relevant. Closing
