### ISSUE TITLE
NZBGet no longer maintained

### ISSUE THREAD

**Issue by Fossil01** [linuxserver/docker-nzbget#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Repo is archived. Seems like there is a fork which had some updates recently and some people have switched to that one.

https://github.com/paul-chambers/nzbget

### Steps To Reproduce

.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2022-11-27-nzbget/

**Comment by Roxedus** [comment]
Read our thoughts on the fork [here](https://github.com/linuxserver/docker-nzbget/pull/158)
