### ISSUE TITLE
Add nzbToMedia

### ISSUE THREAD

**Issue by sachse** [linuxserver/docker-nzbget#18]
Post-processing scripts, [nzbToMedia](https://github.com/clinton-hall/nzbToMedia) especially, would be a very welcome addition to this container. It seems to require the following packages though:
- unrar (already in the container)
- unzip
- tar (already in the container)
- 7zr (p7zip)
- ffmpeg

**Comment by zaggash** [comment]
Hi,

Here is how I deal with nzbtomedia.
Create a file named userscript.sh in your container config folder, with this content :

`#!/bin/bash
apt-get install -y git python

GIT_APP_FOLDER="/app/nzbToMedia"
CONF_APP_FOLDER="/config/nzbToMedia"
if [[ -d "$GIT_APP_FOLDER/.git" ]]
then
  git -C $GIT_APP_FOLDER pull
else
  git clone https://github.com/clinton-hall/nzbToMedia.git $GIT_APP_FOLDER
fi

mkdir -p $CONF_APP_FOLDER
[[ ! -f "$CONF_APP_FOLDER/autoProcessMedia.cfg" ]] && cp $GIT_APP_FOLDER/autoProcessMedia.cfg.spec $CONF_APP_FOLDER/autoProcessMedia.cfg
[[ ! -h "$GIT_APP_FOLDER/autoProcessMedia.cfg" ]] && ln -s $CONF_APP_FOLDER/autoProcessMedia.cfg $GIT_APP_FOLDER/autoProcessMedia.cfg
[[ ! -f "$GIT_APP_FOLDER/logs/nzbtomedia.log" ]] && { mkdir -p $GIT_APP_FOLDER/logs && touch $GIT_APP_FOLDER/logs/nzbtomedia.log; }

chown -R abc.abc /config /app
`

Obviously you can add more package to the "apt-get install"if you need to.

**Comment by zaggash** [comment]
Do not foet to add the variable `-e ADVANCED_SCRIPT='true' `when launching you container

**Comment by zaggash** [comment]
Deprecated solution since it use Apline and advanced script is no longer available

**Comment by Ankh-** [comment]
Any ideas how to implement git and nzbtomedia to this container? I now have to update manually the nzbtomedia implement it and it seems after a container restart I have to re-implement it again...

**Comment by bbsan2k** [comment]
I created a PR to add a Volume for the Scripts. Standard scripts are not included anymore, but one can add them in the volume

**Comment by sparklyballs** [comment]
I closed the PR, you can add volumes from the create/run line, you don't need to add them for everyone by putting them in the Dockerfile.

**Comment by zaggash** [comment]
FYI, check how I deal with it on my transmission container.

https://github.com/zaggash/docker-transmission/
https://hub.docker.com/r/zaggash/docker-transmission/

**Comment by zjpleau** [comment]
Zaggash, how exactly do you deal with it on your transmission container? I didn't see anything there related. Just trying to get my nzbget container to install ffmpeg and ffprobe so the FailureLink script will work.

Thanks
