### ISSUE TITLE
cannot install ffmpeg

### ISSUE THREAD

**Issue by hroman73** [linuxserver/docker-nzbget#20]
I am setting this up new and trying to get the postprocess scripts to run but need to install ffmpeg and ffprobe but cannot.

**Comment by zaggash** [comment]
Hello,

You can use the variable `-e  ADVANCED_SCRIPT:='true'` ans then set a script named userscript.sh in your /config folder wit hthe following content :
```

#!/bin/bash
apt-get install -y ffmpeg
```

**Comment by hroman73** [comment]
that worked thanks

**Comment by RaymondMouthaan** [comment]
An update to this is:

Create a script `userscript.sh` in your `/config/custom-cont-init.d` with the following content:

```
#!/bin/bash
apk add --no-cache ffmpeg
```
