### ISSUE TITLE
python is missing

### ISSUE THREAD

**Issue by bbsan2k** [linuxserver/docker-nzbget#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)][linuxserverurl]
	

If I map my scripts to /app/scripts they can not be executed because python and some python dependencies are missing.
Proposal would be to rebase this image to alpine-python

**Comment by sparklyballs** [comment]
python is already in this image.
