### ISSUE TITLE
Unable to download from usenetserver

### ISSUE THREAD

**Issue by manderso7** [linuxserver/docker-nzbget#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 ubuntu 16.04
Create:docker create --name nzbget -p 6789:6789 -e PUID=1002 -e PGID=1002 -e TZ=Americas/NewYork -v /home/manderso/nzbget/config:/config -v /mnt/downloads_nas/usenet/:/downloads linuxserver/nzbget

Run:docker run -d linuxserver/nzbget

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1002
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO] nzbget 17.1 server-mode
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1002
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO] nzbget 17.1 server-mode
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[INFO] Stopping, please wait...
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1002
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO] nzbget 17.1 server-mode
[INFO] Reloading...
[INFO] nzbget 17.1 server-mode
[INFO] CouchPotato connected to test connection
[INFO] CouchPotato connected to drop off OBFUSCATEDFORMYOWNPROTECTION.nzb.nzb.
[INFO] Adding collection OBFUSCATEDFORMYOWNPROTECTION.nzbto queue
[INFO] Collection OBFUSCATEDFORMYOWNPROTECTION.nzb added to queue
[ERROR] Could not receive data on socket: ErrNo 11, Resource temporarily unavailable
[ERROR] Connection to usenetserver (news.usenetserver.com) failed: Connection closed by remote host
[WARNING] Blocking usenetserver (news.usenetserver.com) for 10 sec
[ERROR] Could not receive data on socket: ErrNo 11, Resource temporarily unavailable
[ERROR] Connection to usenetserver (news.usenetserver.com) failed: Connection closed by remote host
[ERROR] Could not receive data on socket: ErrNo 11, Resource temporarily unavailable
[ERROR] Connection to usenetserver (news.usenetserver.com) failed: Connection closed by remote host
[ERROR] Could not receive data on socket: ErrNo 11, Resource temporarily unavailable
[ERROR] Connection to usenetserver (news.usenetserver.com) failed: Connection closed by remote host

Negative.

Thanks for the help!

**Comment by j0nnymoe** [comment]
A quick look at this issue is that it doesn't look like an issue with the container, more of an issue of where you are trying to connect to. Please try another usenet server and see if that fixes it.

**Comment by manderso7** [comment]
Totally my fault, didn't click ssl when I put an encrypted port for the server. Sorry to waste your time.

**Comment by j0nnymoe** [comment]
@manderso7 No problem, glad you got it working :)
