### ISSUE TITLE
update mechanism

### ISSUE THREAD

**Issue by Benni-chan** [linuxserver/docker-nzbget#4]
since the last update of this container (including the universal installer, i think), the integrated update search works. i used it to update to nzbget 16 (testing). but after a restart of the container, nzbget 15 stable is installed again.
would be nice, if your automatic install/update script on container-statup will recognize the update to the testing version.

**Comment by sparklyballs** [comment]
I have just tested this myself...
since the last update there is a variable called TESTING which if you add to your template (if you're on unraid) or your run command with -e TESTING=1 should install latest testing version...

if you can also confirm this, i'll add to the readme on the main page.

**Comment by Benni-chan** [comment]
adding the variable helped.

**Comment by sparklyballs** [comment]
as an additional note... if you're on testing version and change your mind and want to return to stable branch... removing the variable will do that.
