### ISSUE TITLE
How can I bind to port 80/443?  (re: access denied)

### ISSUE THREAD

**Issue by sofakng** [linuxserver/docker-nzbget#40]
I'm using a bunch of LinuxServer.io containers with macvlan to give each container an external/routable IP address. 

However, if I try to bind to privileged ports (80/443) it gets access denied. 

I've tried adding the NET_BIND_SERVICE cap but it doesn't help.  I've also tried not using the PUID and PGID variables but it also doesn't help. 

I think LinuxServer.io uses S6 overlays and such so I'm not sure how I can get this working...

**Comment by aptalca** [comment]
I haven't used macvlan. Is it essentially using net=host on a separate ip? Can you not map ports? 

Nzbget would have to run as root (puid 0) to bind to ports below 1024. But we do not recommend running them as root, as it often causes other issues, and is a security risk especially when you open it up to internet through port 80.

I would highly recommend using the letsencrypt (or the plain nginx if you have your own certs) and reverse proxying the other apps with additional security through htpasswd

**Comment by sofakng** [comment]
Thanks for the reply. Yes, macvlan is like host networking but you can't remap ports. (ie. -p doesn't do anything) 

I am using nginx as a reverse proxy but I also wanted to use 80/443 for local access and convenience.

**Comment by sofakng** [comment]
Also, you don't need to run as root to bind to privileged ports. You can add the capability by using --cap-add NET_BIND_SERVICE with docker but it doesn't work with the Linux server.io containers for some reason.

**Comment by j0nnymoe** [comment]
Is this still an issue?

**Comment by ruok5** [comment]
I was able to bind to port 80 after executing the following inside the running container:
`apk add --update libcap`
`setcap cap_net_bind_service=+ep /app/nzbget/nzbget`

Now to learn enough about Docker to make this persistent the right way.

**Comment by j0nnymoe** [comment]
This isn't something we would support. If you want to add this functionality to the container, the best thing to do is fork our github repo and make the changes you need and build an image from that.
