### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by phybersplice** [linuxserver/docker-nzbget#47]
I was wondering if you can include a binary of ffmpeg, ffprobe and git in your next build?
I'd like to use the nzbToMedia scripts from Clinton Hall. 

https://github.com/clinton-hall/nzbToMedia

I've included the log of when it extracts a file.
It can't find ffprobe, ffmpeg or git binaries.
All three binaries would be helpful.

https://pastebin.com/7h2D5QFF

Thanks!

**Comment by sparklyballs** [comment]
not something we currently consider viable

you are welcome to fork the repository and add those dependencies yourself

**Comment by phybersplice** [comment]
I did that.
Great learning experience.

Thanks
