### ISSUE TITLE
startup.sh

### ISSUE THREAD

**Issue by Itsmmai** [linuxserver/docker-nzbget#49]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hi, I'm trying to make my docker image as automatic as possible and now I want to start a apk while starting. In my onzu docket image I can create a a file called startup.sh with the command: apk add --no-cache ffmpeg ffmpeg-libs in it at that works.

Is there a way to do this in your image ?

Kind regards
Abel

**Comment by Itsmmai** [comment]
I also mis par2. is there another program used for this ?

**Comment by sparklyballs** [comment]
nzbget has par2 baked in
