### ISSUE TITLE
Init Loop

### ISSUE THREAD

**Issue by flqw** [linuxserver/docker-nzbget#5]
Using the latest version, i run into an init loop with the following repeating in the log file:
```
cat: /downloads/nzbget.lock: No such file or directory
tail: : invalid PID
```

Might be caused by the change made in https://github.com/linuxserver/docker-nzbget/commit/4c9c978436bbbac14123808a358db76015764e6f that added quotes around the PID argument.

**Comment by sparklyballs** [comment]
just built latest version from git and no issues with init loop with ubuntu 14.04 as docker host.

will try docker create method pulling directly from hub next.

**Comment by flqw** [comment]
I use the image on my Synology NAS and just pulled the newest images from the hub. Before that everything worked great.

**Comment by sparklyballs** [comment]
running from the exec command line within the nzbget docker itself.

test="$(cat /downloads/nzbget.lock)" && echo $test
77

i'm wondering whether your PGID/PUID settings don't have permissions to write to the folder where the lock file is being placed.

**Comment by flqw** [comment]
Permissions look ok. When should the lock-file be created? If I create the lock-file manually in the mapped /downloads folder, it gets deleted by the script in *30_remove_lockfile.sh* and then again runs into the file not found exception.

**Comment by sparklyballs** [comment]
the remove script cleans up any old lockfiles that may be present from last shutdown. 
the lockfile is then created by nzbget itself when it runs.
the tail to the log is to stop nzbget relaunching itself because it's running in daemon mode.

can you run ls -lah on the downloads folder and ls -lah on the parent folder for downloads and tell me your PGID/PUID settings and how those relate to users on your synology please.

**Comment by flqw** [comment]
PID and UID of the downloads and config folders do match with the host system and the user has full permissions.  Attaching to the container and starting nzbget in server mode does work. However, if i try to start it in daemon mode with the command copied from the start script
``/sbin/setuser abc /app/nzbget -D -c /config/nzbget.conf``
it won't start and the nzbget.log file contains the following error:
``Starting daemon failed: could not create lock-file /var/run/nzbget.lock``

**Comment by flqw** [comment]
Ok found it. The config file contained the wrong lock file location. Might be because i came from a version that had the lock file not in the download folder yet.

**Comment by sparklyballs** [comment]
we will look at this

**Comment by flqw** [comment]
Ok thanks for the fast support. Love your docker images.
