### ISSUE TITLE
Should support python3, some plugin need python3 evn

### ISSUE THREAD

**Issue by zhsyourai** [linuxserver/docker-nzbget#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by thelamer** [comment]
First off sorry for the delay in responding to this issue, but can you make a compelling argument for why we should include python3 and possibly some pip deps ? 
Specifically how would it help the userbase of this container?

**Comment by computerfr33k** [comment]
I would definitely like python 3 to be installed seeing as python 2.7 is EOL 2020-01-01

https://devguide.python.org/#branchstatus

**Comment by thelamer** [comment]
@computerfr33k but the big question is why ? 
Is there are popular plugin or suite of plugins that require this? 
Our images are here to cover the 99% of users , if someone needs to customize them they can either build locally or bind mount config logic scripts to `/etc/cont-init.d/99-custom`
The question was and still remains , is there a compelling reason the majority of users need this installed by default.

**Comment by computerfr33k** [comment]
I know [nzbToMedia](https://github.com/clinton-hall/nzbToMedia) is pretty popular, which uses python.

I definitely think there is a compelling reason python3 is needed due to python2 being installed by default and it becoming EOL starting next year. Also, why is there so much push back on installing python3 when python2 is installed by default?

**Comment by thelamer** [comment]
I would not call it pushback, just need a reason to make changes to a container. 

We do have plans to deal with Python3 before end of year, but understand these are initiatives that span many repos we control and fall in line with formal announcements on our blog. More recently python3 has had multiple upstream issues in Alpine 3.9, most of them have been worked through like random core dumps on arm64, but we are going to essentially Y2K this one and wait until we have to convert before EOY.
