### ISSUE TITLE
Scheduler Not Working

### ISSUE THREAD

**Issue by Nalith** [linuxserver/docker-nzbget#6]
I have configured my scheduler as per my old environment to stop downloads at 7 in the morning and initiate the downloads at midnight however it does not seem to be initiating any of the scheduled tasks. From my log files it seems the time is correct. I'm running this as an unRaid  Docker.

**Comment by lonix** [comment]
There is this thing somewhere in the settings to adjust the timezone that is not quite obvius. You have to setup a task, and see how delayed the run was, then adjust accordingly.

This is due to failt of the new universal installer they made.

**Comment by Nalith** [comment]
Thanks, I managed to get it sorted following your suggestion.

**Comment by tehniemer** [comment]
This is still an issue for me. TZ is set to "America/Chicago" but the scheduler still uses UTC. 

However, the date is reported correctly from inside the container.
![image](https://user-images.githubusercontent.com/11021632/37683601-1fb3e6f2-2c5b-11e8-9f1b-7d313adeb351.png)
