### ISSUE TITLE
pip modules

### ISSUE THREAD

**Issue by elmero1** [linuxserver/docker-nzbget#69]
I use your docker container and a plugin for notification (nzb-notify). Unfortunately the notification plugin need additional pip modules:
apprise >= 0.7.0
pynzbget
chardet

Is it possible to include this in your container?

**Comment by CHBMB** [comment]
@thelamer @aptalca What do you think?  We can either include the deps or do we defer this to a custom script?

**Comment by thelamer** [comment]
We do it for sab, but that was before custom modification logic existed. 
https://github.com/linuxserver/docker-sabnzbd/blob/master/Dockerfile#L40-L45
The notification stuff does seem like generally accepted as standard issue stuff for users.

**Comment by CHBMB** [comment]
I'll do a PR then. @thelamer
