### ISSUE TITLE
Cant access web address / gui

### ISSUE THREAD

**Issue by mgik20** [linuxserver/docker-nzbget#73]
hi all, a bit stuck with nzbget ... i have it installed in docker using DockSTARTer ... 

192.168.10.63:6789 should be the IP address, but i cannot browse to it

tried reinstalling / rebooting Ubuntu etc, nothing is working

Ubuntu 18.04 / DockSTARTer install

![image](https://user-images.githubusercontent.com/30399415/55281281-ee0e2f80-5310-11e9-9df2-fdc97e0d1157.png)

**Comment by j0nnymoe** [comment]
This isn't dockstarter support.
