### ISSUE TITLE
Unrar not existing

### ISSUE THREAD

**Issue by alphadijkstra** [linuxserver/docker-nzbget#75]
Downloads work, unpacking/unrar doesn't as it can't find the unrar executable as it doesn't exist.
Looking inside the container, unrar can't be found either.

Host OS: QNAP Container Station - Linux
![Screenshot_1](https://user-images.githubusercontent.com/1959447/57028995-d9d78e00-6c40-11e9-89d1-49c7f47d6971.png)

**Comment by aptalca** [comment]
Unrar is in the image: https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile#L72

I have a feeling there is something wrong with your gui settings as nzbget is trying to start `/app/nzbget\unrar.exe` which is not the correct path or the name for the executable.

Are you trying to run custom scripts?

**Comment by alphadijkstra** [comment]
You are 100% correct. Due to me forgetting to tick off 1 the unpack section checkbox when importing the configuration file from a different sabnzb instance, this error occurs.

Thanks for  pointing me in the right direction! :)

**Comment by rmp5s** [comment]
I hate to resurrect a dead thread, but I'm having the exact same problem for the exact same reason.  

I made the epic fail mistake of trying to use an old backup of NZBGet and it's been NOTHING but issues.  I even reinstalled NZBGet and the settings remain.  Not sure how that happens, but I've almost gotten it working...I think this is the last hurdle...

I just have no idea what the paths SHOULD be.

I'm running it in a Docker container on unRAID.  Could I possibly get a screenshot of what the paths should be for the "Unpack" section or something?  I get what is broken and I get why...I just have no idea what needs to go where to actually fix it.  Any assistance greatly appreciated.

**Comment by alphadijkstra** [comment]
Hey rmp5s

These are my current settings within the "unpack" section in the nzbget settings.
Hope this helps you out.

![afbeelding](https://user-images.githubusercontent.com/1959447/102246769-65c62880-3eff-11eb-82a9-034308f6aba6.png)

**Comment by rmp5s** [comment]
> Hey rmp5s
> 
> These are my current settings within the "unpack" section in the nzbget settings.
> Hope this helps you out.
> 
> ![afbeelding](https://user-images.githubusercontent.com/1959447/102246769-65c62880-3eff-11eb-82a9-034308f6aba6.png)

PERFECT...thank you!

It's still failing, though.  Maybe I didn't know what was wrong with it.  lol

Wait a minute...it's looking for "unrar.exe"...that's not going to work.  lol

![image](https://user-images.githubusercontent.com/75582315/102249322-7a82cc00-3ebf-11eb-8403-0cf734251470.png)

Where is unrar that it's supposed to use installed at?

And, could you hit me with a screen shot of your "Paths" tab when you get a second, by chance?  What I did was used a backup from a Windows install...I didn't think about it, but OBVIOUSLY this was a disaster.  Hence it looking for an exe.  

I realized this was a mistake so I removed and deleted the Docker container and Image and re-installed.  All the settings were still there though!!  Not sure why so I've been trying to make it work.  The "Paths" tab has already given me quite a bit of trouble so I'd like to make sure it's good to go...this is what it currently looks like:

![image](https://user-images.githubusercontent.com/75582315/102249045-2546ba80-3ebf-11eb-8161-8c7b1b1fe870.png)

I am thinking something in there isn't right, isn't needed, something like that.

**Comment by rmp5s** [comment]
I THINK it's supposed to be in the /appdata/nzbget folder, but there's nothing in that folder but nzbget.conf...

Maybe I have to put unrar in there?

**Comment by alphadijkstra** [comment]
The only 2 paths thare are different in your config in the paths section seem to be these:
Most likely the scripts path could be the culprit.

![afbeelding](https://user-images.githubusercontent.com/1959447/102253067-2b608980-3f07-11eb-9819-44badd70fd48.png)

**Comment by alphadijkstra** [comment]
Also, your destDir and interDir use a backward slash instead of forward.

**Comment by rmp5s** [comment]
Yup...I noticed the slashes being wrong after posting the pic.  Got that sorted.

I took ".exe" off the end of unrar and 7za aaaaaaaand...

![image](https://user-images.githubusercontent.com/75582315/102254090-70fc6280-3ec5-11eb-9fc9-a3d01f9fe6a7.png)

GREAT SUCCESS!!  Hahaha

Thank you!!

**Comment by alphadijkstra** [comment]
You're welcome! Glad it worked out 👍 Have fun!
