### ISSUE TITLE
Post Processing Performance Very Slow

### ISSUE THREAD

**Issue by carpenike** [linuxserver/docker-nzbget#8]
Hey All,

Not sure where the problem lies, but the same hardware using FreeBSD/Jails was much quicker. I'll have dozens of NZBs downloaded while waiting for a slot in the post processing queue. I believe the docker container is CPU bound and may not be getting enough resources?

Haven't applied any CPU / Memory restrictions on the containers though.

Any thoughts?

**Comment by lonix** [comment]
I Recognize that this is a bit late reply. but as this is not a bug but a request for support, i suggest that you you try our forum and\or our irc channel on #linuxserver.io@freeende.
