### ISSUE TITLE
Two Dockers: Reverse Proxies

### ISSUE THREAD

**Issue by forsomefun2** [linuxserver/docker-nzbget#82]
Sorry if this needs more information
running two dockers

  docker create \
  --name=nzbget \
  --network mynetwork \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Chicago\
  -p 6789:6789 \
  -v /home/snickerpop/.config/nzbget:/config \
  -v /home:/home \
  --restart unless-stopped \
  linuxserver/nzbget

  docker create \
  --name=nzbget \
  --network mynetwork \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Chicago\
  -p 6790:6789 \
  -v /home/snickerpop/.config/nzbget:/config \
  -v /home:/home \
  --restart unless-stopped \
  linuxserver/nzbget

only 1 reverse proxy works 
Is there a way I could get them both to work.

The one that works is the first one.

**Comment by j0nnymoe** [comment]
Well you've named them both the same with the same `/config` mounts. This isn't going to create to seperate containers. Please use our forum or discord for support our containers. Github issues are for used for bugs, not general support.
