### ISSUE TITLE
Extension scripts

### ISSUE THREAD

**Issue by janipewter** [linuxserver/docker-nzbget#84]
I am a complete newbie to Docker. Can anyone please explain how to load extension scripts in the NZBGet Docker? From what I understand, it doesn't have access to the host file system in the normal way. I can't see where the files are and I have no idea where I can put extension scripts so they can be loaded.

Thanks
Jani

**Comment by CHBMB** [comment]
Hi Jani, we reserve Github for bugs/issues rather than support, if you want to hop on to either the forum or Discord that would be better.
