### ISSUE TITLE
Apprise update?

### ISSUE THREAD

**Issue by Tharic99** [linuxserver/docker-nzbget#85]
On this issue, https://github.com/linuxserver/docker-nzbget/issues/69, the various pip modules were added into nzbget and they've been working fantastic.

However, Apprise has recently updated to the 0.8.0 version from the 0.7.9 version.

You can see more info about that here - https://github.com/caronc/apprise/issues/149

It's possible for me to to go into the Docker console of nzbget and issue a `pip install --upgrade apprise` manually of course, but when the container is rebuilt it's not pulling the 0.8.0 version down.

I purged my nzbget container out and downloaded the latest as well, but apprise is still on version 0.7.9 in that latest.

Any ideas how I can get that updated to the 0.8.0 version permanently? I had assumed since it's in the dockerfile https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile it would just pull the latest version, but it doesn't appear to be doing that.

**Comment by aptalca** [comment]
next build of nzbget should have it

**Comment by aptalca** [comment]
It is currently on 0.8.1
