### ISSUE TITLE
Python3 not included

### ISSUE THREAD

**Issue by Spence1115** [linuxserver/docker-nzbget#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

For a while now (nearly a year), nzbToMedia has been warning that as of 01 January 2020 it will no longer support Python2.7, and require Python3 instead. Therefore, it no longer works with this container for nzbget as it is still running on Python2.7.

## Current Behavior

Container should use Python3

## Steps to Reproduce

1. Add nzbToMedia
2. Try to postprocess anything
Will fail due to not including Python3

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by thelamer** [comment]
#89 and #90  when merged , closing
