### ISSUE TITLE
FR - Support for unidecode and py7zr python3 modules, and dependencies for NZBGet scripts

### ISSUE THREAD

**Issue by mmz06** [linuxserver/docker-nzbget#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Feature Request
unidecode module is usefull for a NZBGet script requiring to manipulate filenames using specific french accentuated characters
p7zr module is usefull for a NZBGet pre-processing script to decompress 7z archives
When a script calls for unidecode by using `from unidecode import unidecode`, in a python3 script, unidecode module is correctly imported
When a script calls for py7zr, by using `import py7zr`, in a python3 script, py7zr module is correctly imported.

unidecode module could be directly imported using the following command set from the dockerfile:
`pip3 install unidecode`

py7zr module could be directly imported using the following command set from the dockerfile:
`pip3 install -U pip setuptools`
`apk add --no-cache --upgrade --virtual=build-dependencies gcc g++`
`pip3 install py7zr`

## Current Behavior
Modules are missing so import fails in the scripts

## Steps to Reproduce
None

## Environment
**OS:**Unraid OS / Linux Slackware      
**CPU architecture:** x64
**How docker service was installed:**      
Via Community Application menu which creates the container

## Command used to create docker container (run/create/compose/screenshot)
None

## Docker logs
None

**Comment by Toucan-Sam** [comment]
For what it's worth, if anyone else comes here looking because all of their scripts have failed:
Roll back to 'linuxserver/nzbget:v21.1-r2311-ls48' until resolved.

**Comment by TLS2000** [comment]
Confirmed.  Rolled back to 'linuxserver/nzbget:v21.1-r2311-ls48' and my VideoSort script started working again.

**Comment by mmz06** [comment]
> Thanks Toucan-Sam -- I'm finding that urllib2 is missing in latest and that is borking two scripts

Hi, 
It seems not exactly related to my original query, anyway, from what I can say, it seems your issue is related to the fact NZBGet now uses Python 3.8 as default, instead of the old Python 2.7, with is now "unset" [https://www.python.org/doc/sunset-python-2/].
You should try to open a support ticket to the NZBGet VideoSort GitHub instead of here:
--> [https://github.com/nzbget/VideoSort]

**Comment by jpartain89** [comment]
This is happening with every extension, seeing as they all seem to be lacking in updates from their developers...

**Comment by mouzzampk2014** [comment]
Hi, its happening with nzb-notify too as this is missing 
`pip install six`
